name: 'Bundle Addon'
description: 'Create a .mcpack or .mcaddon file from the repository contents'
inputs:
  pack-name:
    description: 'Name of the pack to create'
    required: true
  directory:
    description: 'Directory to include in the pack'
    required: true
    default: './*'

runs:
  using: 'composite'
  steps:
    - name: Deprecation Warning
      run: echo "This branch (main) is deprecated and will be removed in the future. Please use a versioned branch like v1 instead."
      shell: bash
    - name: Create pack from directory
      id: zip-pack
      run: |
        INITIAL=$(pwd)
        cd ${{ inputs.directory }}
        zip -r $INITIAL/${{ inputs.pack-name }} ./*
        cd $INITIAL
      shell: bash
