name: 'Upload Pack as Artifact'
description: 'Uploads a pack as an artifact to be used in other workflows'
inputs:
  pack-name:
    description: 'Name of the pack to upload'
    required: true

outputs:
  artifact-url:
    description: 'URL of the uploaded artifact'
    value: ${{ steps.upload-artifact.outputs.artifact-url }}

runs:
  using: 'composite'
  steps:
    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.pack-name }}
        path: ${{ inputs.pack-name }}

    - name: Output Artifact URL
      id: output-artifact-url
      run: echo "artifact-url=${{ steps.upload-artifact.outputs.artifact-url }}" >> "$GITHUB_OUTPUT"
      shell: bash
